export const wordList = [
  {
    id: 1,
    en: "Monk",
    bd: "ভান্তে",
    audio: "/ref-sounds/1.wav",
  },
  {
    id: 2,
    en: "Physician",
    bd: "বৈদ্য",
    audio: "/ref-sounds/2.wav",
  },
  {
    id: 3,
    en: "Woman physician",
    bd: "অঝা",
    audio: "/ref-sounds/3.wav",
  },
  {
    id: 4,
    en: "Teacher",
    bd: "মাজ্‌তর",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 5,
    en: "Father",
    bd: "বাব",
    audio: "/ref-sounds/5.wav",
  },

  {
    id: 6,
    en: "Father-in-law",
    bd: "শোর",
    audio: "/ref-sounds/6.wav",
  },
  {
    id: 7,
    en: "Mother-in-law",
    bd: "শোরী",
    audio: "/ref-sounds/7.wav",
  },
  {
    id: 8,
    en: "Uncle",
    bd: "হাক্কা",
    audio: "/ref-sounds/8.wav",
  },
  {
    id: 9,
    en: "Uncle",
    bd: "মামু",
    audio: "/ref-sounds/9.wav",
  },
  {
    id: 10,
    en: "Elder, senior",
    bd: "জেত্‌",
    audio: "/ref-sounds/10.wav",
  },
  {
    id: 11,
    en: "Younger, junior",
    bd: "হনেত্‌",
    audio: "/ref-sounds/11.wav",
  },

  {
    id: 12,
    en: "Husband",
    bd: "নেক",
    audio: "/ref-sounds/12.wav",
  },
  {
    id: 13,
    en: "Wife",
    bd: "মোক্‌",
    audio: "/ref-sounds/13.wav",
  },
  {
    id: 14,
    en: "Brother",
    bd: "ভেই",
    audio: "/ref-sounds/14.wav",
  },
  {
    id: 15,
    en: "Sister",
    bd: "ভোন",
    audio: "/ref-sounds/15.wav",
  },
  {
    id: 16,
    en: "Son",
    bd: "পুঅ",
    audio: "/ref-sounds/16.wav",
  },

  {
    id: 17,
    en: "Daughter",
    bd: "ঝি",
    audio: "/ref-sounds/17.wav",
  },
  {
    id: 18,
    en: "Neighbours",
    bd: "পাড়াল্যে",
    audio: "/ref-sounds/18.wav",
  },
  {
    id: 19,
    en: "Old, aged",
    bd: "বুড়ো",
    audio: "/ref-sounds/19.wav",
  },
  {
    id: 20,
    en: "Chest",
    bd: "বুগ",
    audio: "/ref-sounds/20.wav",
  },
  {
    id: 21,
    en: "Belly",
    bd: "পেত্‌",
    audio: "/ref-sounds/21.wav",
  },
  {
    id: 22,
    en: "Neck",
    bd: "গত্তনা",
    audio: "/ref-sounds/22.wav",
  },

  {
    id: 23,
    en: "Forehead",
    bd: "হবাল",
    audio: "/ref-sounds/23.wav",
  },
  {
    id: 24,
    en: "Face",
    bd: "মু",
    audio: "/ref-sounds/24.wav",
  },
  {
    id: 25,
    en: "Skin",
    bd: "চাম",
    audio: "/ref-sounds/25.wav",
  },
  {
    id: 26,
    en: "Mad",
    bd: "পাগল",
    audio: "/ref-sounds/26.wav",
  },
  {
    id: 27,
    en: "Blind",
    bd: "কান্‌",
    audio: "/ref-sounds/27.wav",
  },

  {
    id: 28,
    en: "Fever",
    bd: "জর",
    audio: "/ref-sounds/28.wav",
  },
  {
    id: 29,
    en: "Head ache",
    bd: "মাধা ঘুরোনী",
    audio: "/ref-sounds/29.wav",
  },
  {
    id: 30,
    en: "illness",
    bd: "অসুগ",
    audio: "/ref-sounds/30.wav",
  },
  {
    id: 31,
    en: "Button",
    bd: "বোদাম",
    audio: "/ref-sounds/31.wav",
  },
  {
    id: 32,
    en: "Pillow",
    bd: "বালোজ",
    audio: "/ref-sounds/32.wav",
  },
  {
    id: 33,
    en: "Bed",
    bd: "বিচ্ছোন",
    audio: "/ref-sounds/33.wav",
  },

  {
    id: 34,
    en: "Amulet",
    bd: "তাবিদ",
    audio: "/ref-sounds/34.wav",
  },
  {
    id: 35,
    en: "Ornament of gold",
    bd: "সোনালংকার",
    audio: "/ref-sounds/35.wav",
  },
  {
    id: 36,
    en: "Stair, ladder",
    bd: "সাঙু",
    audio: "/ref-sounds/36.wav",
  },
  {
    id: 37,
    en: "Room",
    bd: "গুধি",
    audio: "/ref-sounds/37.wav",
  },
  {
    id: 38,
    en: "Kitchen hall",
    bd: "পিজোর   ---",
    audio: "/ref-sounds/38.wav",
  },

  {
    id: 39,
    en: "Celling",
    bd: "মাজা",
    audio: "/ref-sounds/39.wav",
  },
  {
    id: 40,
    en: "wall",
    bd: "বেড়",
    audio: "/ref-sounds/40.wav",
  },
  {
    id: 41,
    en: "Fance",
    bd: "ঘিরে",
    audio: "/ref-sounds/41.wav",
  },
  {
    id: 42,
    en: "Candle",
    bd: "মুম বাত্তি",
    audio: "/ref-sounds/42.wav",
  },
  {
    id: 43,
    en: "Pot",
    bd: "পিলে",
    audio: "/ref-sounds/43.wav",
  },
  {
    id: 44,
    en: "Lock",
    bd: "তালা",
    audio: "/ref-sounds/44.wav",
  },


  {
    id: 45,
    en: "Key",
    bd: "চাভি",
    audio: "/ref-sounds/45.wav",
  },
  {
    id: 46,
    en: "Spoon",
    bd: "চামেজ",
    audio: "/ref-sounds/46.wav",
  },
  {
    id: 47,
    en: "Glass",
    bd: "গলঝ",
    audio: "/ref-sounds/47.wav",
  },
  {
    id: 48,
    en: "Rice",
    bd: "চোল",
    audio: "/ref-sounds/48.wav",
  },
  {
    id: 49,
    en: "Vegetables",
    bd: "তোন্‌-পাত্‌",
    audio: "/ref-sounds/49.wav",
  },

  {
    id: 50,
    en: "Fish",
    bd: "মাজ",
    audio: "/ref-sounds/50.wav",
  },
  {
    id: 51,
    en: "Litchi",
    bd: "লেঝু",
    audio: "/ref-sounds/51.wav",
  },
  {
    id: 52,
    en: "Guava",
    bd: "গোয়েম",
    audio: "/ref-sounds/52.wav",
  },
  {
    id: 53,
    en: "Cocoanut",
    bd: "নারেকুল",
    audio: "/ref-sounds/53.wav",
  },
  {
    id: 54,
    en: "Pine apple",
    bd: "আনাজ",
    audio: "/ref-sounds/54.wav",
  },
  {
    id: 55,
    en: "Date palm",
    bd: "হাঝুর",
    audio: "/ref-sounds/55.wav",
  },

  {
    id: 56,
    en: "Lemon",
    bd: "লেমু",
    audio: "/ref-sounds/56.wav",
  },
  {
    id: 57,
    en: "White",
    bd: "ধুপ",
    audio: "/ref-sounds/57.wav",
  },
  {
    id: 58,
    en: "Black",
    bd: "হালা",
    audio: "/ref-sounds/58.wav",
  },

  {
    id: 59,
    en: "Green",
    bd: "য়েল",
    audio: "/ref-sounds/59.wav",
  },
  {
    id: 60,
    en: "Nevey blue",
    bd: "সোজ  ---- ",
    audio: "/ref-sounds/60.wav",
  },
  {
    id: 61,
    en: "Ash colour",
    bd: "ছেয়ো রং",
    audio: "/ref-sounds/61.wav",
  },
  {
    id: 62,
    en: "Dim",
    bd: "মরা মরা রং",
    audio: "/ref-sounds/62.wav",
  },
  {
    id: 63,
    en: "Magnet",
    bd: "লুঅ",
    audio: "/ref-sounds/63.wav",
  },
  {
    id: 64,
    en: "Magnet",
    bd: "চম্বগ",
    audio: "/ref-sounds/64.wav",
  },

  {
    id: 65,
    en: "Tin",
    bd: "তোন",
    audio: "/ref-sounds/65.wav",
  },
  {
    id: 66,
    en: "Tree",
    bd: "গাজ",
    audio: "/ref-sounds/66.wav",
  },
  {
    id: 67,
    en: "Snake",
    bd: "সাব",
    audio: "/ref-sounds/3.wav",
  },
  {
    id: 68,
    en: "King fisher",
    bd: "মা রাঙা",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 69,
    en: "Heron",
    bd: "বগা",
    audio: "/ref-sounds/5.wav",
  },

  {
    id: 70,
    en: "Crow",
    bd: "হবা",
    audio: "/ref-sounds/1.wav",
  },
  {
    id: 71,
    en: "Owl",
    bd: "পেজা",
    audio: "/ref-sounds/2.wav",
  },
  {
    id: 72,
    en: "Dove",
    bd: "কঅ",
    audio: "/ref-sounds/3.wav",
  },
  {
    id: 73,
    en: "Pigeon",
    bd: "কোদোর",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 74,
    en: "Watch man",
    bd: "চোগিদার",
    audio: "/ref-sounds/5.wav",
  },
  {
    id: 75,
    en: "Servent",
    bd: "চাগর",
    audio: "/ref-sounds/5.wav",
  },


  {
    id: 76,
    en: "Advocate",
    bd: "উগিল",
    audio: "/ref-sounds/1.wav",
  },
  {
    id: 77,
    en: "Singer",
    bd: "গান গেয়্যে",
    audio: "/ref-sounds/2.wav",
  },
  {
    id: 78,
    en: "Driver",
    bd: "গাড়ি চালেয়্যে",
    audio: "/ref-sounds/3.wav",
  },
  {
    id: 79,
    en: "Barber",
    bd: "নাবিদ",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 80,
    en: "Loan",
    bd: "উধোর‌",
    audio: "/ref-sounds/5.wav",
  },

  {
    id: 81,
    en: "Seller",
    bd: "বেজিয়্যে",
    audio: "/ref-sounds/1.wav",
  },
  {
    id: 82,
    en: "Buyer",
    bd: "কিনিয়্যে",
    audio: "/ref-sounds/2.wav",
  },
  {
    id: 83,
    en: "Load",
    bd: "ভোত্তি",
    audio: "/ref-sounds/3.wav",
  },
  {
    id: 84,
    en: "Unload",
    bd: "হালি",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 85,
    en: "I",
    bd: "মুই",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 86,
    en: "you",
    bd: "তুই",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 87,
    en: "He",
    bd: "তে",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 88,
    en: "They",
    bd: "তারা",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 89,
    en: "this",
    bd: "ইয়ান",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 90,
    en: "Task/ work",
    bd: "হাম",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 91,
    en: "Done",
    bd: "গজ্ঝে",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 92,
    en: "Who",
    bd: "হন্না",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 93,
    en: "There",
    bd: "শিয়দ",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 94,
    en: "When",
    bd: "হমলে",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 95,
    en: "Will go",
    bd: "জেম",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 96,
    en: "Today",
    bd: "ইজ্জে",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 97,
    en: "Did you Eat?",
    bd: "হিয়ুজ",
    audio: "/ref-sounds/4.wav",
  },
  {
    id: 98,
    en: "Good",
    bd: "গম",
    audio: "/ref-sounds/4.wav",
  }
];

// export const wordList = ["hello", "dear"];
